my_stack = []
my_stack.append('x')
my_stack.append('y')
my_stack.append('z')
print(my_stack)
print('\n elements poped from my_stack')
print(my_stack.pop())
print(my_stack.pop())
print(my_stack.pop())                
print(" \nmy_stack after elements are poped ",my_stack)
